# Set seed for reproducibility
set.seed(123)

# Create the data frame with additional keywords
critical_words_df <- data.frame(
  Topic = c(
    rep("Race and Racism", 25),
    rep("Sex and Sexism", 25),
    rep("Poverty", 25),
    rep("Gender", 25),
    rep("Anti-Blackness", 25),
    rep("Anti-Semitism", 23)
  ),
  Keyword = c(
    "racism", "privilege", "microaggression", "intersectionality", "colorblindness", "discrimination", "bias", "stereotype",
    "segregation", "diversity", "inclusion", "equity", "allyship", "xenophobia", "ethnocentrism", "assimilation", "multiculturalism",
    "prejudice", "implicit", "explicit", "systemic", "institutional", "internalized", "marginalization", "othering",
    
    "sexism", "patriarchy", "misogyny", "feminism", "harassment", "objectification", "equality", "empowerment",
    "consent", "mansplaining", "gaslighting", "victim-blaming", "slut-shaming", "gender-bias", "wage-gap", "glass-ceiling",
    "double-standard", "stereotyping", "discrimination", "underrepresentation", "marginalization", "toxic-masculinity", "male-gaze",
    "intersectionality", "femininity",
    
    "poverty", "inequality", "unemployment", "homelessness", "welfare", "deprivation", "marginalization", "exclusion",
    "gentrification", "food-insecurity", "malnutrition", "illiteracy", "underemployment", "debt", "social-mobility", "class",
    "socioeconomic", "income", "wealth-gap", "cyclical", "systemic", "working-poor", "minimum-wage", "social-safety-net", "austerity",
    
    "gender", "transgender", "cisgender", "nonbinary", "queer", "identity", "expression", "fluidity",
    "dysphoria", "transition", "pronouns", "genderqueer", "agender", "bigender", "two-spirit", "androgyny", "genderfluid",
    "misgendering", "deadnaming", "binarism", "heteronormativity", "lgbtqia+", "intersex", "drag", "gender-neutral",
    
    "antiblackness", "segregation", "profiling", "tokenism", "oppression", "disenfranchisement", "redlining", "colorism",
    "microaggression", "stereotype", "discrimination", "bias", "prejudice", "racism", "systemic", "institutional", "structural",
    "marginalization", "intersectionality", "privilege", "white-supremacy", "police-brutality", "mass-incarceration", "racial-wealth-gap",
    "environmental-racism",
    
    "antisemitism", "scapegoating", "holocaust", "prejudice", "xenophobia", "bigotry", "discrimination", "stereotyping",
    "hate-speech", "persecution", "genocide", "diaspora", "zionism", "anti-zionism", "blood-libel", "conspiracy", "tokenism",
    "othering", "marginalization", "microaggression", "islamophobia", "interfaith", "assimilation"
  ),
  Score = round(runif(148, min = -1, max = 1), 2),
  Definition = c(
    "Prejudice based on race",
    "Unearned advantages based on identity",
    "Subtle discriminatory comments or actions",
    "Interconnected nature of social categorizations",
    "Ignoring racial differences",
    "Unfair treatment based on race",
    "Prejudice in favor of or against one group",
    "Oversimplified image of a particular type",
    "Separation or isolation of a race or class",
    "Inclusion of different types of people",
    "Act of including all types of people",
    "Fairness and justice in procedures and outcomes",
    "Supportive association with marginalized group",
    "Fear or hatred of foreigners",
    "Evaluating other cultures by one's own cultural standards",
    "Adoption of dominant culture's values and behaviors",
    "Coexistence of diverse cultural groups",
    "Preconceived opinion not based on reason",
    "Unconscious attitudes affecting behavior",
    "Conscious and intentional prejudice",
    "Racism embedded in social structures",
    "Racism within established institutions",
    "Acceptance of negative stereotypes about one's own group",
    "Treatment as insignificant or peripheral",
    "Viewing or treating a person or group as intrinsically different",
    
    "Prejudice based on sex",
    "System where men hold primary power",
    "Hatred or contempt for women",
    "Advocacy for women's rights and equality",
    "Aggressive pressure or intimidation",
    "Treating a person as a commodity",
    "State of being equal in status or rights",
    "Process of becoming stronger and more confident",
    "Permission for something to happen or agreement to do something",
    "Explaining something to a woman in a condescending way",
    "Manipulating someone into questioning their own sanity",
    "Suggesting a victim is partly responsible for their own abuse",
    "Criticizing women for perceived sexual activity",
    "Unfair lean toward one gender over another",
    "Disparity in earnings between men and women",
    "Invisible barrier to advancement in a profession",
    "Rule or standard applied differently between sexes",
    "Assigning oversimplified characteristics to a group",
    "Unfair treatment based on sex",
    "Inadequate presence in a field or sector",
    "Treatment as insignificant or peripheral",
    "Harmful cultural norms associated with masculinity",
    "Depicting the world from a masculine point of view",
    "Interconnected nature of social categorizations",
    "Traits associated with being female",
    
    "State of lacking sufficient money or resources",
    "Uneven distribution of resources",
    "State of not having a paid job",
    "Condition of lacking stable housing",
    "Government support for those in need",
    "State of being severely lacking in basic needs",
    "Treatment as insignificant or peripheral",
    "Process of not allowing participation",
    "Renovation leading to an influx of wealthy residents",
    "Lack of reliable access to sufficient food",
    "Lack of proper nutrition",
    "Inability to read or write",
    "Insufficient employment",
    "Owing money",
    "Ability to move between social classes",
    "Social standing or grouping",
    "Relating to social and economic factors",
    "Money received on a regular basis",
    "Large disparity in wealth between groups",
    "Recurring nature of poverty",
    "Embedded in social systems",
    "Employed but still in poverty",
    "Lowest wage permitted by law",
    "Public financial support systems",
    "Reduction in government spending",
    
    "Socially constructed characteristics of sexes",
    "Person whose gender differs from birth sex",
    "Person whose gender matches birth sex",
    "Gender identity not exclusively male or female",
    "Umbrella term for non-heterosexual orientations",
    "One's concept of self as male, female, or neither",
    "External manifestation of one's gender",
    "Dynamic nature of gender identity",
    "Distress due to mismatch between gender and sex",
    "Process of changing one's gender presentation",
    "Words used to refer to a person's gender",
    "Non-binary gender identity",
    "Lacking gender identification",
    "Identifying as both male and female",
    "Non-Western cultures' non-binary gender",
    "Combination of masculine and feminine characteristics",
    "Gender identity that varies over time",
    "Referring to someone by wrong gender",
    "Using a transgender person's birth name",
    "Belief in only two genders",
    "Assumption that heterosexuality is the norm",
    "Acronym for sexual and gender minorities",
    "Born with sex characteristics of both sexes",
    "Cross-dressing performance art",
    "Not specific to one gender",
    
    "Prejudice specifically against Black people",
    "Separation or isolation of a race or class",
    "Using race as a basis for suspicion",
    "Symbolic effort towards inclusivity",
    "Prolonged cruel or unjust treatment",
    "Deprivation of power to participate in political process",
    "Discriminatory denial of services based on race",
    "Discrimination based on skin shade",
    "Subtle discriminatory comments or actions",
    "Oversimplified image of a particular type",
    "Unfair treatment based on race",
    "Prejudice in favor of or against one group",
    "Preconceived opinion not based on reason",
    "Prejudice based on race",
    "Racism embedded in social structures",
    "Racism within established institutions",
    "Fundamental racism in society's structure",
    "Treatment as insignificant or peripheral",
    "Interconnected nature of social categorizations",
    "Unearned advantages based on identity",
    "Belief in superiority of white people",
    "Excessive force by law enforcement against Black individuals",
    "Disproportionate imprisonment of Black people",
    "Economic disparity between racial groups",
    "Policies causing environmental harm to minorities",
    
    "Hostility or prejudice against Jews",
    "Blaming a group for societal problems",
    "Genocide of European Jews in World War II",
    "Preconceived opinion not based on reason",
    "Fear or hatred of foreigners",
    "Intolerance towards those with different opinions",
    "Unfair treatment based on group membership",
    "Widely held but oversimplified image of a group",
    "Abusive or threatening speech targeting specific groups",
    "Harassment or ill-treatment based on identity",
    "Deliberate killing of a large group of people",
    "Scattered population with a common origin",
    "Movement for development of Jewish state",
    "Opposition to the state of Israel",
    "False accusation historically used against Jews",
    "Belief in a secret plan by a group",
    "Symbolic effort towards inclusivity",
    "Viewing or treating a person or group as intrinsically different",
    "Treatment as insignificant or peripheral",
    "Subtle discriminatory comments or actions",
    "Prejudice against Muslims",
    "Cooperation between different religions",
    "Adoption of dominant culture's values and behaviors"
  )
)

# Display the first few rows of the data frame
head(critical_words_df)

# save the data frame to a CSV file
write.csv(critical_words_df, "data/critical_words_dataset.csv", row.names = FALSE)

